### ISSUE TITLE
set-output warnings and node12 deprecation

### ISSUE THREAD

**Issue by hargut** [dapr/setup-dapr#106]
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
https://github.com/dapr/setup-dapr/blob/main/package.json#L31 // needs @actions/core >= v1.10.0

https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
https://github.com/dapr/setup-dapr/blob/main/action.yml#L15

**Comment by hargut** [comment]
https://github.com/dapr/setup-dapr/pull/93

**Comment by paulyuk** [comment]
This was FIXED by #142.  thank you for raising the concerns here.
