### ISSUE TITLE
Update project to use Node 20

### ISSUE THREAD

**Issue by FlorentATo** [dapr/setup-dapr#141]
Node 16 is no longer supported by GitHub since Septembre 2023. Please consider updating the project to use Node 20.

Ref: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

Note: This issue supersedes https://github.com/dapr/setup-dapr/issues/106

**Comment by paulyuk** [comment]
Fixed! thank you for feedback
